### ISSUE TITLE
IntegerObject: Document and ensure its 32 bit

### ISSUE THREAD

**Issue by imphil** [cocotb/cocotb#1202] opened 2019-11-20 23:10 UTC
`IntegerObject` is used to set int/integer nets as defined in SystemVerilog, which are 32 bit (signed) values. See https://github.com/cocotb/cocotb/issues/268 for a discussion on signed-ness.

- `IntegerObject` doesn't check the size, which could lead to loss of data.
- We need to document that `IntegerObject` is 32 bit.
- Our backend functionality, starting with `simulator.set_signal_val_long`, uses long instead of int as data type and in the function names. That should be cleaned up to say int.

**Comment by elgorwi** [comment] 2020-04-30 03:05
Looking into this issue and just opened an initial PR. I developed this using Modelsim (32-bit) on windows Msys2 platform. Initial compilation of the C++ libs (no local changes) revealed an issue, that is probably caused by using a 32-bit platform. I compiled this on OSX (64-bit platform) as well without any compilation warnings:
```
    cocotb/share/lib/vhpi/VhpiCbHdl.cpp: In member function 'virtual int VhpiSignalObjHdl::set_signal_value(long int, gpi_set_action_t)':
    cocotb/share/lib/vhpi/VhpiCbHdl.cpp:579:24: warning: comparison of integer expressions of different signedness: 'long int' and 'unsigned int' [-Wsign-compare]
      579 |             if ((value > EnumLimits::max()) || (value < EnumLimits::min())) {
          |                  ~~~~~~^~~~~~~~~~~~~~~~~~~
    cocotb/share/lib/vhpi/VhpiCbHdl.cpp:579:55: warning: comparison of integer expressions of different signedness: 'long int' and 'unsigned int' [-Wsign-compare]
      579 |             if ((value > EnumLimits::max()) || (value < EnumLimits::min())) {
          |                                                 ~~~~~~^~~~~~~~~~~~~~~~~~~
    cocotb/share/lib/vhpi/VhpiCbHdl.cpp:589:24: warning: comparison of integer expressions of different signedness: 'long int' and 'unsigned int' [-Wsign-compare]
      589 |             if ((value > IntLimits::max()) || (value < IntLimits::min())) {
          |                  ~~~~~~^~~~~~~~~~~~~~~~~~
    cocotb/share/lib/vhpi/VhpiCbHdl.cpp:589:54: warning: comparison of integer expressions of different signedness: 'long int' and 'unsigned int' [-Wsign-compare]
      589 |             if ((value > IntLimits::max()) || (value < IntLimits::min())) {
          |                                                ~~~~~~^~~~~~~~~~~~~~~~~~
```
This warning is relevant when changing ```simulator.set_signal_val_long``` to only accept 32-bit values. It looks like "long" is not the same size on 32-bit and 64-bit platforms. 
Interestingly, vhpi is expecting an unsigned int```typedef uint32_t vhpiIntT;``` where vpi is expecting a signed int ```typedef int             PLI_INT32;```
Should we cast the value checks VhpiCbHdl.cpp to int64_t to get rid of the warnings above? Or should we remove the value checks altogether because we would only be accepting signed 32-bit values through ```simulator.set_signal_val_long``` anyway?  
I don't have access to a vhpi simulator to see if a direct cast would cause any undesired side effects.

**Comment by ktbarrett** [comment] 2020-04-30 13:17
@elgorwi You may also look at #268. There is some discussion on that.

`long` means different things on different systems, on 32 bit systems and 64 bit Windows `long` is 32 bit, most everywhere else they are 64 bit. To err on the safe side we really should be using `int32_t` for `set_signal_value_long`. In the case of assigning to Verilog `integer`s or VHDL `integer`/`natural` etc. we are limited to 32 bit integers anyway. Assuming that `set_signal_value_long` is how we appropriately set integer signals, supporting more than 32 bits is likely bad.

One potential issue is how to support integer types that *are* 64 bit integers (I think Verilog 2005 changed integers to 64 bit, but not many simulators followed suit).

Were you planning on making this change in the already open PR?

**Comment by elgorwi** [comment] 2020-05-01 00:27
> 
> 
> @elgorwi You may also look at #268. There is some discussion on that.
> 
> `long` means different things on different systems, on 32 bit systems and 64 bit Windows `long` is 32 bit, most everywhere else they are 64 bit. To err on the safe side we really should be using `int32_t` for `set_signal_value_long`. In the case of assigning to Verilog `integer`s or VHDL `integer`/`natural` etc. we are limited to 32 bit integers anyway. Assuming that `set_signal_value_long` is how we appropriately set integer signals, supporting more than 32 bits is likely bad.
> 
> One potential issue is how to support integer types that _are_ 64 bit integers (I think Verilog 2005 changed integers to 64 bit, but not many simulators followed suit).
> 
> Were you planning on making this change in the already open PR?

@ktbarrett Thanks for the input. I'll open another pull request to handle changes to ```simulator.set_signal_val_long```

**Comment by elgorwi** [comment] 2021-01-09 06:36
Fixed by #2316

**Closed** 2021-01-09 16:19 UTC
Labels: category:codebase:gpi, type:bug
