### ISSUE TITLE
qrun for Questa

### ISSUE THREAD

**Issue by raysalemi** [cocotb/cocotb#2498] opened 2021-03-28 17:48 UTC
I'm not sure how wedded you are to an identical flow for modelsim and questa, but questa now has the qrun command which compiles files of any extension properly. It also manages file order and incremental compilation.

It may be worth an upgrade for questa users.

**Comment by imphil** [comment] 2023-05-19 15:02
Duplicate of #2852

**Closed by imphil** 2023-05-19 15:02 UTC
Labels: type:feature, category:simulators:questa, category:codebase:project-automation
