### ISSUE TITLE
VCS reports "segamentation fault“ when python has some simple typo.

### ISSUE THREAD

**Issue by zlzg12345** [cocotb/cocotb#1508] opened 2020-03-19 09:53 UTC
Hi, 
When we wrote some simple examples to run them with VCS, 
we find VCS report the below "segment fatal" even it just has some simple typo in python testcase. 
Is it possible to make those errors report in python interprator rather than VCS ?
```
//VCS  fatal. 
"An unexpected termination has occurred in sim_build/simv due to a signal: Segmentation fault"

//Python typo 
class c_i2s_driver(BusDriver):
    '''
    I2S Driver
    '''
    _signals = ["bclk", "ws", "txd", "rxd"]
    .....
    self.bus.w_ws <= 1         //the testcase passed if we fix typo from "w_ws" to "ws"
```

**Comment by eric-wieser** [comment] 2020-03-19 10:07
Duplicate of #1261

**Closed by eric-wieser** 2020-03-19 10:07 UTC
Labels: type:bug
