### ISSUE TITLE
ability to force/freeze signal

### ISSUE THREAD

**Issue by s3bs** [cocotb/cocotb#657] opened 2018-09-01 10:18 UTC
rather than just being able to deposit signals, it is helpful to force signals inside a design. 
Would be great if cocotb would support that.
Maybe as an signalname attribute.
`dut.signalname._force = 1`

**Comment by lukedarnell** [comment] 2018-09-26 02:40
@s3bs we have a change that implements force, freeze, deposit and release.

The syntax is:
` dut.stream_in_ready <= Force(1)`
` dut.stream_in_ready <= Release()`
`dut.stream_in_ready <= Deposit(BinaryValue('x'))`
`dut.stream_in_ready <= Freeze()`

@chiggs @stuarthodgson Does that syntax make sense?

**Comment by lukedarnell** [comment] 2018-10-28 22:51
Ok, I will do a pull request with the changes.

**Comment by cmarqu** [comment] 2018-11-06 20:56
Duplicate of #472.

**Comment by cmarqu** [comment] 2018-11-06 21:06
Force/release would allow us to build a tool for what is called "testbench qualification" or "mutation coverage" - inject an error into the design, run a regression test and check that at least one of the tests finds the injected error. If the error is not detected, the testbench is too sloppy.

We could start by injecting stuck-at faults at the DUT ports (I have a pull request coming up for providing ``_is_port`` and ``_port_direction`` attributes for discovered objects).

This could be a good project for something like Google's Summer of Code.

**Comment by ashmanskas** [comment] 2019-02-25 21:36
If I understand correctly, force/release would also make it possible (by overriding connected inputs) to embed a unit test of a single module into a testbench whose main job is to test the larger design, which I would find quite appealing. 
If I understand correctly, unit-testing a non-top-level module now requires a separate Makefile, a separate invocation of cocotb (hence a separate scoreboard printout), and for all practical purposes a separate directory in which to run it.

**Comment by tonywmnix** [comment] 2019-06-16 17:26
Is there a pull request somewhere for this? This would be helpful to me..

Somewhat related, is there a way to issue tcl commands to the ucli prompt in VCS? Something like:

`cocotb.send_tcl_command("force dut.rst_n 1'b0")`

**Comment by imphil** [comment] 2019-06-16 20:20
> Is there a pull request somewhere for this? This would be helpful to me..

no, but please feel free to do one yourself!

> Somewhat related, is there a way to issue tcl commands to the ucli prompt in VCS? Something like:

No, it's not. cocotb interacts only through VPI (and similar interfaces) with the simulator; so you'd need to find the equivalent VPI function to force a signal.

**Comment by lukedarnell** [comment] 2019-06-17 01:35
@imphil @tonywmnix we do have changes with this functionality implemented as documented earlier in this issue.
I'll try and get a pull request to you in the next couple of days.

**Comment by themperek** [comment] 2019-08-16 15:41
@lukedarnell Any update on this?

**Comment by lukedarnell** [comment] 2019-08-17 13:17
I have a working patch for this but only for verilog / VPI.
Haven’t had time to look at the VHDL side of things yet.
Should I just do a pull request for the verilog part?

**Comment by themperek** [comment] 2019-08-17 13:54
I would be interested in any case to use it personally for error injection. If we can merge is different story.

**Comment by ashmanskas** [comment] 2019-08-17 15:48
I am eager to give it a try, at this point for Verilog simulation using Cadence IUS.  I expect this capability to be very useful, but I won't know for sure until I try it out.  I would think that if the VPI patch proves useful enough, someone may eventually be motivated to extend the functionality to VHPI.  The perfect is the enemy of the good.

**Comment by themperek** [comment] 2019-09-13 09:52
@thasti are you willing to help porting? I can help.

**Comment by thasti** [comment] 2019-09-13 11:45
@lukedarnell Thank you for sharing, I'll take a look! @themperek Yes, I'd be willing to help. Will come back to you as soon as I have an overview.

**Closed** 2020-02-21 10:25 UTC
Labels: type:feature
