### ISSUE TITLE
Running the endian example fails

### ISSUE THREAD

**Issue by Protoplasmoloid** [cocotb/cocotb#1542] opened 2020-03-28 15:31 UTC
When I try to run the endian-swapper example, as below, I get:

$ make SIM=ghdl TOPLEVEL_LANG=VHDL
***snip***
     0.00ns INFO     cocotb                                      __init__.py:161  in _initialise_testbench           Seeding Python random module with 1585407922
     **0.00ns CRITICAL cocotb.regression                         regression.py:153  in initialise                      Failed to import module test_endian_swapper_hal: No module named 'hal'**
     0.00ns INFO     cocotb.regression                         regression.py:154  in initialise                      MODULE variable was "test_endian_swapper.

OS is Ubuntu 18.04LTS running in VirtualBox, 64bit. I have also tried this on Ubuntu 18.04LTS on a 32bit laptop, similar issue.
Any help appreciated, 
Thanks.

**Comment by eric-wieser** [comment] 2020-03-28 15:42
Duplicate of #1539, there's a typo in the makefile. Patch welcome!

**Closed by eric-wieser** 2020-03-28 15:42 UTC
