### ISSUE TITLE
Python _imp__*

### ISSUE THREAD

**Issue by reedjosh** [cocotb/cocotb#226] opened 2015-04-04 10:29 UTC
Hey guys,

This this is likely just my lack of knowledge. I've been trying to get cocotb running for use on Windows, and I've not had any luck. I'm an intern, and this is one of my tasks. 

I've got mingw, python, and iverilog installed. When I run the makefile in the tests folder I get several issues of the form:

io_module.o:io.c:(.text+0x10e): undefined reference to '_imp__PyErr_Occured'

I've installed swig as well, but I may have done so incorrectly. I've also tried making the distutils.cfg file and libpython.a file, but with no luck.

**Comment by reedjosh** [comment] 2015-04-04 10:54
![image](https://cloud.githubusercontent.com/assets/9508385/6992359/395686d2-da7e-11e4-80a2-c747b0b1fbd4.png)

**Comment by stuarthodgson** [comment] 2015-04-04 15:07
Hi,

Could you just confirm that you are running version 1.0.0?

Stu

**Comment by reedjosh** [comment] 2015-04-04 18:40
![image](https://cloud.githubusercontent.com/assets/9508385/6994057/63337f28-dabf-11e4-9c30-b4c9808aca8f.png)

**Comment by reedjosh** [comment] 2015-04-04 18:42
Is 1.0.0 different than 1.0?

**Comment by potentialventures** [comment] 2015-04-04 20:36
No it's not. I'm away from home at the moment so won't be able to look at
this until Monday afternoon GMT. It's not an error I've seen and im more
concerned about the error from ld rather than the symbols.

Can you try the functionally test by rubbing make in
examples/functionality/tests please. The error you are seeing is in
building a lib for a test case not a cocotb library. So may not impact you
using the framework.

Stu

**Comment by reedjosh** [comment] 2015-04-04 20:43
![image](https://cloud.githubusercontent.com/assets/9508385/6994487/9a46ff4c-dad0-11e4-8262-e64e774a24fe.png)

**Comment by reedjosh** [comment] 2015-04-04 20:44
Here you are sir. Thanks for the quick support. I'm pretty novice with a lot of these tools, so please don't hesitate to tell me if I do something stupid.

**Comment by jeremyherbert** [comment] 2015-04-05 00:05
Hi reedjosh,

Could you post your Python version? python --version is the command you
want.

**Comment by reedjosh** [comment] 2015-04-05 00:39
![image](https://cloud.githubusercontent.com/assets/9508385/6995266/937d18d8-daf1-11e4-962e-02068609fe5e.png)

**Comment by jeremyherbert** [comment] 2015-04-05 03:16
Ok, how about this one?

python -c "import platform; print platform.architecture()"

**Comment by reedjosh** [comment] 2015-04-05 03:44
![image](https://cloud.githubusercontent.com/assets/9508385/6995660/5f78991c-db0b-11e4-8f23-fe601fc3c268.png)

**Comment by elgorwi** [comment] 2015-04-06 10:28
Ok, note the endian-swapper HAL cosimulation example currently doesn't run under windows. 
However, the non-cosimulation related tests of the endian swapper example should work fine under windows. 
Could you try copying the cocotb dir from /home/josh/cocotb to c:/cocotb and 'make clean' and then 'make' again?
What output do you get when running 'which gcc' and 'which python'?
Also, which python distribution did you install?

**Comment by themperek** [comment] 2019-10-16 07:30
#1099

**Comment by themperek** [comment] 2020-04-16 07:18
In the current development version, windows support should be better now.
Please also check https://docs.cocotb.org/ for instructions.

Since this issue is from 2015 I am closing but feel free to reopen in case the issue is still there.

**Closed by themperek** 2020-04-16 07:18 UTC
Labels: category:windows
