### ISSUE TITLE
Performance regression test

### ISSUE THREAD

**Issue by stuarthodgson** [cocotb/cocotb#126] opened 2014-04-30 15:55 UTC
While working on concretely defining the lower GPI/VPI/VHPI layers it noticed it would be good to have a test that runs for a few seconds and does lots of callbacks but did not have any randomization so a idea of a performance regression could be ascertained.

**Comment by cmarqu** [comment] 2019-07-23 17:56
See also #961.

**Comment by garmin-mjames** [comment] 2020-03-20 23:48
#1502 new example `matrix_multiplier` is designed to have a `BinaryValue`-heavy performance regression test.

**Comment by garmin-mjames** [comment] 2020-09-10 22:53
Now that #1502 is merged, we should extract the performance numbers for each CI run on master and graph them over time somewhere.

Stretch goal would be a performance-related CI check or bot post for PRs.

**Comment by ktbarrett** [comment] 2020-09-11 00:20
Performance on CI is tricky since we don't control the machines we do the CI on. Performance can fluctuate if they give us a VM running on older hardware or there is heavy usage one afternoon, etc. I'm open to possible solutions.

**Comment by garmin-mjames** [comment] 2020-09-11 00:24
@ktbarrett I would expect the graph to be rather spiky due to the issues you mention, but it would at least give us a trend to look at.
It'd be nice to have a dedicated hardware setup to run this on to remove more variables.

**Comment by ktbarrett** [comment] 2020-09-11 00:31
Is there a free tool we could use to gather and do analysis on metrics?

**Comment by garmin-mjames** [comment] 2020-09-11 00:43
`matrix_multiplier` is also only one data point. It's very `BinaryValue`-heavy. I'll try to get a profile graph like in #961 of it on master.

**Comment by ktbarrett** [comment] 2020-09-11 00:49
Well I mean is there some online tool where we can upload regression artifacts (logs, profiling databases, etc.), perform analysis, and graph performance in real-time on some kind of dashboard? Just being able to dump the regression artifacts somewhere would be nice. Should we do that with another github repo? Or is there a better solution out there?

**Comment by garmin-mjames** [comment] 2020-09-11 00:59
Every project that I've seen that tracks performance metrics have had one-off setups to graph a couple of key things. Often it's a developers machine and uploaded somewhere for public access. That being said there are probably solutions out there, I just don't know what they are.

**Comment by ktbarrett** [comment] 2024-02-26 20:24
We now have https://cocotb.github.io/cocotb-benchmark-results/dev/bench/.

**Closed by ktbarrett** 2024-02-26 20:24 UTC
Labels: type:feature, category:performance
