### ISSUE TITLE
Icarus Compatibility Bug

### ISSUE THREAD

**Issue by Devil-SX** [cocotb/cocotb#3913] opened 2024-06-02 02:52 UTC
While using the Icarus backend, the unknown value is represented by the lowercase 'x', but the Cocotb framework only supports resolving the uppercase 'X' as an integer.

Error:
```
 Unresolvable bit in binary string: 'x'
```

**Comment by ktbarrett** [comment] 2024-06-02 04:26
This has nothing to do with uppercase or lowercase, this is BinaryValue functioning as intended. Some function you are using requires casting the BinaryValue to a 0/1 value. Throwing an error is the default behavior.

I'm sure what you are doing is comparing the BinaryValue, right? That attempts to convert it to an integer for comparison. It sucks =/ Which is why 2.0 is moving to LogicArray. You can cast BinaryValues to LogicArrays: `LogicArray(handle.value)` and things might work a little more intuitively.

**Closed by ktbarrett** 2024-06-02 04:26 UTC
