### ISSUE TITLE
Version 1.9 fails to work with Verilator when --trace option is used

### ISSUE THREAD

**Issue by Derrick-Derrickson** [cocotb/cocotb#4141] opened 2024-08-28 12:08 UTC
Using cocotb 1.9, Verilator 5.022/5.029 and python 3.10.
asking for a trace dump from a simple counter results in the error message:
`Vtop.cpp:125: Turning on wave traces requires Verilated::traceEverOn(true) call before time 0.`
Downgrading to 1.8.1 fixes this issue with no other changes made.

**Comment by ktbarrett** [comment] 2024-08-28 13:53
Dupe of #4088.

This has been fixed on the 1.9 branch, but hasn't been released yet. Try `pip install git+https://github.com/cocotb/cocotb.git@stable/1.9` at least until v1.9.1 is released.

**Closed by ktbarrett** 2024-08-28 13:53 UTC
