### ISSUE TITLE
Issues with BinaryRepresentation and endianess in BinaryValue

### ISSUE THREAD

**Issue by higgns** [cocotb/cocotb#1219] opened 2019-12-02 18:50 UTC
A script to demonstrate the issue:
```python
from cocotb.binary import BinaryRepresentation, BinaryValue

value = 5
n_bits = 8
big_endian = False
print("value=%s, n_bits=%s, big_endian=%s" % (value, n_bits, big_endian))

twos_comp = BinaryValue(value=value, n_bits=n_bits, bigEndian=big_endian,
                        binaryRepresentation=BinaryRepresentation.TWOS_COMPLEMENT)
print("twos_comp \t= %s" % twos_comp.binstr)

signed_mag = BinaryValue(value=value, n_bits=n_bits, bigEndian=big_endian,
                        binaryRepresentation=BinaryRepresentation.SIGNED_MAGNITUDE)
print("signed_mag \t= %s" % signed_mag.binstr)

if value >= 0:
    unsigned = BinaryValue(value=value, n_bits=n_bits, bigEndian=big_endian,
                        binaryRepresentation=BinaryRepresentation.UNSIGNED)
    print("unsigned \t= %s" % unsigned.binstr)
```
Output:
```
value=5, n_bits=8, big_endian=False
twos_comp       = 00000101
signed_mag      = 0000101
unsigned        = 00000101
```
length of `signed_mag.binstr` is weird, but number is correct

```
value=5, n_bits=8, big_endian=True
twos_comp       = 11111010
signed_mag      = 1000010
unsigned        = 10100000
```
only unsigned is correct, both others are wrong

```
value=-5, n_bits=8, big_endian=False
twos_comp       = 11111011
signed_mag      = 1000101
```
values are good
```
value=-5, n_bits=8, big_endian=True
twos_comp       = 11111101
signed_mag      = 1000011
```
With big endian, both negative results are wrong.

**Comment by eric-wieser** [comment] 2019-12-02 19:19
I think this is a duplicate of #608.

**Closed** 2019-12-02 19:19 UTC
Labels: status:duplicate
