### ISSUE TITLE
Error while accessing typedef structures via cocotb 

### ISSUE THREAD

**Issue by PiyushSaini07** [cocotb/cocotb#3202] opened 2023-01-26 18:20 UTC
Hi,

I've started using typedef structures in verilog for accessing memory. 
For example :
```
typedef struct packed {
logic field_1;
logic field_2;
logic field_3;
logic [4:0] test_reg;
} reg_t;

typedef struct packed {
reg_t reg1;
reg_t reg2;
} blk_t;

blk_t blk; //create a variable of blk_t type
```

In verilog, if I want to access field_1 in reg1 I would do `blk.reg1.field_1 = 1'b0;`
The same is possible via cocotb.

However, I'm facing issue when I want to access complete register via cocotb
Verilog allows `blk.reg1 = 8'hAB;`
But cocotb throws error for this statement as it could not find the signal I'm trying to assign the value. Is it possible to replicate the same behavior in cocotb?

**Comment by marlonjames** [comment] 2023-01-26 23:29
Currently it is not possible to assign a single value to the packed struct in that way. cocotb treats the struct as a hierarchy element containing other variables/signals.

**Comment by ktbarrett** [comment] 2023-01-28 13:59
Dupe of #435.

**Closed** 2023-01-29 17:07 UTC
Labels: status:duplicate, category:codebase:gpi, category:codebase:handle
